### ISSUE TITLE
Discuss how to make application work with v2 & v3 cf api

### ISSUE THREAD

**Issue by KlapTrap** [SUSE/stratos#1]
Initial thoughts
* Work on an api interface model.
* Most of the work should be done in the reducers and effects
* The store structure shouldn't change
  * Provide mapping to keep entity keys constant  
  * This should shelter the components from the api changes and let us develop components without worrying about the api versions.

This work may make us able to handle future versions too.

@richard-cox Lets put our thoughts/note here

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1543
