### ISSUE TITLE
Cloud Foundry Permissions

### ISSUE THREAD

**Issue by KlapTrap** [SUSE/stratos#10]
* Disabled actions which the user can't do at the moment but can if they take an action themselves
* Hide actions which the user can't do without someone else changing roles
* Should take into account new admin read only and global auditor states
* Should take into account new disabled organisation/space
* See https://docs.cloudfoundry.org/concepts/roles.html

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1538
