### ISSUE TITLE
Tabs widget wraps when shrunk horizontally

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#101]
With a bit of tweaking we can wrap the tabs, however afterwards the selected indicator (white bar under tab text) does not position correctly (selector appears under second row when first row item is selected).

There are two types of [tabs](https://material.angular.io/components/tabs/overview)..
1.  `<mat-tab-group>` - Requires tab content to be supplied in the same page. Disables wrap and applies scrolling/pagination to tabs (woohoo!). 
2. `<nav mat-tab-nav-bar>` - Shows tab content in router `<router-outlet>`, allows routes. Doesn't handle wrapping at all

We need the later for the router.

There's an angular-material [issue](https://github.com/angular/material2/issues/2177) to ensure parity between the two approaches, but it's been open for a year and no sign of fixing.

We'll probably need to provide our own solution as per V1

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1502
