### ISSUE TITLE
Migrate to stratos-ui

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#118]
- Create new branch in stratos-ui for v2 master (master-v2?)
- migrate, with history, stratos v2 master
- migrate issues along with labels/milestones/etc
- will need to update 
  - Travis
  - code climate (will this work against suse org??)

**Comment by richard-cox** [comment]
@hamzahamidi Just a quick heads up, we're migrating V2 (master of this repo) over to the [cloud foundry stratos repo](https://github.com/cloudfoundry-incubator/stratos) in the next few days. After that any future V2 contributions should be made to that repo.

**Comment by hamzahamidi** [comment]
Thank you for reminding me @richard-cox

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1496
