### ISSUE TITLE
Ensure app summary pages loading and fetching is correct

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#127]
- Should show loading indicator for only the requests required to show the first tab
- Should not load or wait for request for data that is needed for other tabs
- Other tabs should load data when shown

**Comment by richard-cox** [comment]
- Should locate the fetch/update observables in app service and not tab base

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1490
