### ISSUE TITLE
Improve list components set up and use

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#128]
- Folder structure should pair data source and configs together
- Dynamically add the 'select' and 'actions' column given the amount of relevant actions
- Review location of sort configuration. Should these and filters be in the column definitions?
- Move location of dispatch SetListStateAction to abstract List class. Ensure we default to table
- convert ctor for list config class to object to allow for descriptions and better optional params (review which of these should be optional)
- If no sort config is supplied hide the sort widget

**Comment by richard-cox** [comment]
- If no sort config is supplied hide the sort widget

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1489
