### ISSUE TITLE
Update delete app process to cover associated items

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#131]
When we delete an app we also need to take into account any bound routes, service instances, etc
Two cases
- Simple case (no routes, service instances, etc). Needs a confirmation modal
- Complicated case (with routes, services instances). Need a two step approach. Step 1 deletes app, step 2 offers to unbind + delete any bound routes, service instances, etc

**Comment by KlapTrap** [comment]
We should use the "extraReducers" in api-request-reducers.generator.ts to do this.

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1488
