### ISSUE TITLE
Fix copy button in code block

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#133]
Contents need to wrap OR position of copy button needs to be fixed to top right to avoid not scrolling

**Comment by KlapTrap** [comment]
An example of what's happening:
<img width="991" alt="screen shot 2018-01-22 at 11 26 54" src="https://user-images.githubusercontent.com/2823726/35218613-2ebcefb6-ff67-11e7-8781-78719b10103e.png">

We should avoid scrolling within this element.
