### ISSUE TITLE
Non-local list: Search field looses focus when the list makes a request. 

### ISSUE THREAD

**Issue by KlapTrap** [SUSE/stratos#134]
This is particularly annoying when you're free text searching and take a break from typing for a second.

**Comment by KlapTrap** [comment]
It's because we disable the search field when a fetch is happening. I would be good to check if we can just not disable the field without the list pagination getting into a bad state (e.g. overlapping searches happening at the same time).

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1487
