### ISSUE TITLE
Create basic introduction to dev docs

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#160]
How to...
- Make a request
- Monitor the status of that request
- Fetch the result/entities of the response

**Comment by KlapTrap** [comment]
Me: Take a look at https://stackoverflow.com/questions/42946659/angular-2-compodoc-serving-docs-on-github-pages & https://compodoc.github.io/compodoc/

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1478
