### ISSUE TITLE
Kubernetes dashboard not appearing when enabled

### ISSUE THREAD

**Issue by jeremy-moffitt** [SUSE/stratos#177]
### Frontend Deployment type

* [ ] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, using docker compose
* [ ] Docker, single container deploying all components
* [x] npm run start
* [ ] Other (please specify below)
used canary branch

### Backend (Jet Stream) Deployment type

* [ ] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, using docker compose
* [ ] Docker, single container deploying all components
* [x] Other (please specify below)
running ./jetstream in a local dev environment
used canary branch

### Expected behaviour
If the K8s dashboard is enabled on a K8s deployment that Stratos has an endpoint for, the dashboard should appear embedded in the Stratos UI

may be related to https://github.com/SUSE/stratos/issues/151 , unclear though I've seen it working previously in other environments

### Actual behaviour
the Kubernetes plugin shows up, but the dashboard does not appear in the submenu and is not embedded

### Steps to reproduce the behavior
enable the K8s dashboard on a CaaSP or other K8s deployment , then connect Stratos to that environment (create a Kubernetes endpoint for it)

### Log output covering before error and any error statements
No specific errors were observed

**Comment by jeremy-moffitt** [comment]
One of the SOC cloud engineers tried this after having seen it in the demo from @nwmac  and @richard-cox  but was unable to get the dashboard to load. When Neil tried it he ran into an issue that may or may not have been the same thing... filed this to track it , and possibly have someone local pick it up as an investigation to work on

**Comment by eapodaca** [comment]
Tried this with minikube with the dashboard deployed manually via their yml file. Dashboard still does not show up in the kubernetes plugin UI.

**Comment by richard-cox** [comment]
@jeremy-moffitt @eapodaca At the moment the feature is disabled. Which of the steps in #151 did you try in order to enable it?

**Comment by jeremy-moffitt** [comment]
@richard-cox I dont have more details and @eapodaca  has been buried in unrelated work, I understand Gloria reached out and that the feature isnt complete yet. Is there additional feature work to do here or is it largely testing and validation? In either case, is this something that is in-progress or is it something someone might be able to use as a learning experience in Stratos development?

**Comment by nwmac** [comment]
This has been resolved in version 3.0.0
