### ISSUE TITLE
App Wall reloads apps on every visit

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#19]
- New application list data source created onInit
- data source ctor sets list pag/sort/filter settings
- 'change' of pag/sprt/filter settings detected and a new request is made

Should tackle, or keep in mind, during https://github.com/SUSE/stratos/issues/5

**Comment by KlapTrap** [comment]
This will be fixed in #71

**Comment by richard-cox** [comment]
Fixed as per #71
