### ISSUE TITLE
After stopping the app the instances table/running counts are incorrect

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#190]
Could be something to do with app service not returning stats when not running (though this doesn't cover the stats table).
We also (incorrectly) make a stats call regardless of running state during polling. This fails and the stats remain in the store. We need to not make this call and when a successful stop command is sent clear the stat entities and pagination sections

Also need to check to see how V1 handles same case

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1463
