### ISSUE TITLE
Add basic tooltips, where appropiate, to mat-icons

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#193]
Now we have a growing range of icons (app wall, app summary pages, endpoints, etc) we're using some more obscure ones and overloading others. Some very small and basic tooltips should be used to guide the user. This seems to be an accepted material design pattern for icons - https://material.io/guidelines/components/tooltips.html#

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1462
