### ISSUE TITLE
Helm tab in tech preview should be unrelated to helm repository endpoints

### ISSUE THREAD

**Issue by HartS** [SUSE/stratos#204]
In the tech preview, a Helm tab appears when the user adds a helm repository in the endpoints page. However, the newly revealed helm tab contains integration with the kube endpoints' helm releases which may be entirely unrelated to the repository endpoint added. For example, even if you add a repository with no charts, all installed releases (whether installed from local files or from other repositories) will still be shown, and can be managed. Since much of the functionality here is independent of whether a helm repository endpoint has been added, it may be useful to always display this tab when there's a connected kube/caasp cluster, and charts can be displayed as well after repositories have been added

**Comment by nwmac** [comment]
This was fixed in version 3.0.0 with the new Workloads view
