### ISSUE TITLE
Page Title is "SUSE CAP" (and other branding qualms)

### ISSUE THREAD

**Issue by agracey** [SUSE/stratos#232]
### Frontend Deployment type

* [ ] Cloud Foundry Application (cf push)
* [x] Kubernetes, using a helm chart
* [ ] Docker, single container deploying all components
* [ ] npm run start
* [ ] Other (please specify below)

### Backend (Jet Stream) Deployment type

* [ ] Cloud Foundry Application (cf push)
* [x] Kubernetes, using a helm chart
* [ ] Docker, single container deploying all components
* [ ] Other (please specify below)

### Expected behaviour
Branding should be CaaSP/CAP agnostic when not installed as part of CAP install.

As Stratos supports CaaSP without CAP as a deployment method, there might be some confusion from customers who didn't buy cap and are now seeing it in there environment.

### Actual behaviour
Branding is CAP specific

### Log output covering before error and any error statements
```
Insert log hereCopy
```

**Comment by nwmac** [comment]
Fixed in 2.7.0
