### ISSUE TITLE
Generic way to handle errors

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#29]
* Ensure we have all the data we need to handle proxied request errors.
  * In the past we would use 'passthrough' which would mean the request status code and original error messages would be retained. At the moment the status code is lost
  * The suggestion is to not use passthrough to maintain a consistent response format
* Handle errors for the two types of requests we make
  * Errors to entity requests (get, push, etc)
  * Errors to non-entity requests (if applicable after refactor)
* Should cover situations like
  * Fetching data
  * Actions on rows/in list views
  * Full screen modals like create application

Update: PR #196 adds the ability to show status by table row

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1528
