### ISSUE TITLE
Move to Angular 5

### ISSUE THREAD

**Issue by KlapTrap** [SUSE/stratos#3]
Update information: https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced

Migration steps: https://angular-update-guide.firebaseapp.com/

**Comment by richard-cox** [comment]
We need to upgrade to at least @angular/cli v1.6. Older versions have a dependency tree of posscss-url --> directory-encoder --> handlebars which prior to it's v4 had a security issue.

**Comment by KlapTrap** [comment]
Upgrade our angular cli and angular material version too.
