### ISSUE TITLE
V1 Parity: Behaviour of drop downs in create app stepper

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#33]
* Slow loading orgs/spaces. In v1 there were situations where the org and space were slow to fetch. This meant the drop downs would appear to not work for a while without notification to user. To get around this they now have a 'loading' indicator. If we fetch orgs and spaces while showing this screen we need to also have some kind of visual loading indicators
 * Automatically select the first cf with an org and a space (some cf's will not have any orgs and some orgs will not have any spaces).

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1527
