### ISSUE TITLE
cf set-env APP VAR VALUE not shown in Startos 3.1 -> App -> Variables

### ISSUE THREAD

**Issue by ghost** [SUSE/stratos#380]
### Frontend Deployment type

* [x] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, single container deploying all components
* [ ] npm run start
* [ ] Other (please specify below)

### Backend (Jet Stream) Deployment type

* [x] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, single container deploying all components
* [ ] Other (please specify below)

### Expected behaviour
Environment value set with cf set-env should been listed in Stratos -> App -> Variables

### Actual behaviour
Not shown in upper part of the frame for variables set in Stratos, nor in the box below containing all vars.

### Steps to reproduce the behavior
cf push APP
cf set-env APP VAR value
restaget with CLI or Stratos

### Log output covering before error and any error statements
```
Insert log hereCopy
```

**Comment by ghost** [comment]
cf version 6.51.0+2acd15650.2020-04-07

**Comment by richard-cox** [comment]
Hi @phakkarainen, having some problems reproducing this, could I confirm which version of the code you're pushing and that the new env shows up in the cli via `cf env`? The env var list also does not update automatically, you'll need to either hit the refresh button top right in the list or refresh the page.

**Comment by ghost** [comment]
I re-tested and the value can be seen also in Stratos.
I guess I had clicked refresh, but it must be I had not.
Thanks Richard!
