### ISSUE TITLE
Visiting marketplace tab breaks service list

### ISSUE THREAD

**Issue by rschollmeyer** [SUSE/stratos#399]
### Frontend Deployment type

* [x] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, single container deploying all components
* [ ] npm run start
* [ ] Other (please specify below)

### Backend (Jet Stream) Deployment type
* [x] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, single container deploying all components
* [ ] Other (please specify below)

### Expected behaviour

Services list shows all existing services.

### Actual behaviour

When you initially click on the Services tab all services are shown as expected. After clicking the marketplace tab and go back to the Services tab services are sometimes not shown at all (see image and the corresponding error message below). Refreshing the browser on the services page makes the services list works as expected again. 

![broken](https://user-images.githubusercontent.com/24436623/85690780-32cf7480-b6d4-11ea-9f39-3232a941a09a.png)

Note: It occurs in both CF Stratos & Suse Stratos.

### Steps to reproduce the behavior

1. Click Services tab, you will see all services
2. Click Marketplace tab, nothing to do here
3. Click Services tab again, list is broken
4. Refresh the browser on the services page, you will see all services again

### Log output covering before error and any error statements
The browser console shows this error multiple times.
```
ERROR TypeError: "this.serviceInstanceEntity.entity.service_plan.entity.service.entity is undefined"
```

Note: We also opened this issue in the CF Stratos github repository [https://github.com/cloudfoundry/stratos/issues/4397](https://github.com/cloudfoundry/stratos/issues/4397)

**Comment by richard-cox** [comment]
Fix upstream is https://github.com/cloudfoundry/stratos/pull/4417

**Comment by rschollmeyer** [comment]
Closing this since [https://github.com/cloudfoundry/stratos/pull/4417](https://github.com/cloudfoundry/stratos/pull/4417) fixes the issue.
