### ISSUE TITLE
Ca't install Harbor Helm Chart - get stuck on 'Loading'

### ISSUE THREAD

**Issue by nwmac** [SUSE/stratos#499]
Add the SUSE Helm Repository.

Try installing the Harbor Helm Chart - the stepper gets stuck with the "Loading..." message.

![Screenshot 2020-09-22 at 08 46 50](https://user-images.githubusercontent.com/1955897/93856088-5cd30b80-fcb0-11ea-90e5-eb7465da7a24.png)

**Comment by nwmac** [comment]
There's an error in the console log:

```
core.js:6228 ERROR 
YAMLException {name: "YAMLException", reason: "duplicated mapping key", mark: Mark, message: "duplicated mapping key at line 475, column 3:↵      serviceAccountName: ""↵      ^", stack: "YAMLException: duplicated mapping key at line 475,…load (https://127.0.0.1:4200/vendor.js:197636:19)"}
message: "duplicated mapping key at line 475, column 3:↵      serviceAccountName: ""↵      ^"
name: "YAMLException"
reason: "duplicated mapping key"
stack: "YAMLException: duplicated mapping key at line 475, column 3:↵      serviceAccountName: ""↵      ^↵    at 
...
```

**Comment by richard-cox** [comment]
@nwmac Which chart was this? I've reproduced Troy's issue with `argo/argo`, but others like `bitnami/mediawiki` install fine.
