### ISSUE TITLE
Can't go to about page

### ISSUE THREAD

**Issue by nwmac** [SUSE/stratos#5]
### Frontent Deployment type

* [ ] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, using docker compose
* [ ] Docker, single container deploying all components
* [ ] npm run start
* [ ] Other (please specify below)

### Backend (portal-proxy) Deployment type

* [ ] Cloud Foundry Application (cf push)
* [ ] Kubernetes, using a helm chart
* [ ] Docker, using docker compose
* [ ] Docker, single container deploying all components
* [ ] Other (please specify below)

### Log output covering before error and any error statements
```
Insert log hereCopy
```

**Comment by richard-cox** [comment]
@nwmac Tested this today in the now merged branding PR, looks like it's resolved.
