### ISSUE TITLE
Add support for ArtifactHub (the replacement for Helm Hub)

### ISSUE THREAD

**Issue by troytop** [SUSE/stratos#523]
Not sure if this is just a hiccup or if it's an earlier EOL than we expected, but https://hub.helm.sh/ is not returning searches, thus hanging the monocular view in Stratos.

A Monocular compatible search API endpoint has been added to Artifact Hub via https://github.com/artifacthub/hub/pull/598

**Comment by richard-cox** [comment]
- ~~In 4.2 Helm Hub is now disabled by default (to be removed entirely in future release) (https://github.com/SUSE/stratos/issues/524)~~
- ~~In a future release we'll replace the hub functionality with artifact hub~~
- ~~The stratos upstream repo can now be found in Artifact hub - https://artifacthub.io/packages/helm/stratos/console (https://github.com/cloudfoundry/stratos/issues/4645)~~

UPDATE!
- In 4.2 support for Helm hub has been removed (https://github.com/SUSE/stratos/issues/524)
- In 4.2 support for Artifact Hub has been added (https://github.com/cloudfoundry/stratos/pull/4646)
- The stratos upstream repo can now be found in Artifact hub - https://artifacthub.io/packages/helm/stratos/console (https://github.com/cloudfoundry/stratos/issues/4645)
