### ISSUE TITLE
Cloud Foundry: Root View

### ISSUE THREAD

**Issue by KlapTrap** [SUSE/stratos#6]
* Summary panel
* Show list of organisations
* Org actions (edit, delete, ?assign users)
* Cloud foundry global actions
* Create an organisation
* Create a space
* ?Assign users
* ?Show list of users and their roles. Also allow these roles to be edits (covered elsewhere)
* Show firehose with log controller
* Show static table/cards for Feature Flags
* Show static table/cards for Build Packs
* Show static table/cards for Stacks
* Show static table/cards for Security Groups

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1542
