### ISSUE TITLE
Differentiate between user and request errors for auth calls

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#66]
* Differentiate between endpoint connect 401 and generic errors
   * Currently show `Could not connect, please try again` for both
   * Need to show some kind of `unknown username or password combination` style message for 401 errors. 
* Also need to do the same on the log in screen 
   * Could possibly use same component/visual look of endpoint connect log in (?)

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1514
