### ISSUE TITLE
Pattern to force refresh of state at certain nav points

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#67]
For instance, when visiting the endpoints section we should refresh the state in the background. Same goes for app wall, app, etc

**Comment by KlapTrap** [comment]
How about we have a "auto refresh" component that we can put onto a page that will fire off an action at an interval?

**Comment by richard-cox** [comment]
For initial phase create generic refresh button to fire off custom action

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1513
