### ISSUE TITLE
Ability to replace instead of merge request data response

### ISSUE THREAD

**Issue by richard-cox** [SUSE/stratos#68]
- request data merges new content into old
- however there's an issue where an entity/property is removed but due to merge is retained in new state
- for instance if a third party deletes an endpoint and we refresh the state the endpoint will remain. This may also be the case for other delete actions
- need to think if we can differentiate the cases where merge or replace should be used

**Comment by KlapTrap** [comment]
This specific case should be fixed when we use the pagination state for the endpoint table #71. Although the deleted entity will stay in the entity state, the page id array will actually dictate what gets shown. @richard-cox can you think of any other cases this might be a problem?

**Comment by richard-cox** [comment]
I think we'd still need to clear out the stale entities. For instance when we want to create a new endpoint or application and need to use a unique name.. those lists come from all known entities rather than those that were paginated/filtered. I can't think of other specific uses cases yet, but would foresee this as an issue when we update individual entities. We can't rule out the provider removing properties to clear them.

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1512
