### ISSUE TITLE
Cloud Foundry: Manager Users

### ISSUE THREAD

**Issue by KlapTrap** [SUSE/stratos#7]
* Show users and their roles (both org and space)
* Create (stretch)
* Remove (stretch)
* Update
* Assign org and space roles to individual or many users
* Remove org and space roles to individual or many users
* Delete (stretch)
* Does not cover applying user permissions to features (covered in STRAT-189)

**Comment by nwmac** [comment]
This issue was moved to cloudfoundry-incubator/stratos#1541
