### ISSUE TITLE
Update login screen with more generalized message

### ISSUE THREAD

**Issue by troytop** [SUSE/stratos#75]
Filing this against the SUSE version, but possibly also appliccable to upstream. 

Currently we see:

  SUSE Stratos
  Cloud Foundry
  Console
  Use SUSE Stratos to develop, compose, and manage Cloud Foundry workloads.

We should consider changing this to include Kubernetes workloads. Suggest:

  SUSE Stratos
  Console
  Use SUSE Stratos to manage Cloud Foundry and Kubernetes systems and workloads.

Open to other messaging ideas. We basically just want to give people an idea what they'll be able to do once they log in.

**Comment by troytop** [comment]
After discussion with Product Marketing for CAP, we'd like to change the title (currently "SUSE Stratos Cloud Foundry Console") to "SUSE Cloud Application Platform Console"

This might necessitate changing the descriptive text from:

"Use SUSE Stratos to manage Cloud Foundry and Kubernetes systems and workloads."

...to just:

"Manage and monitor Cloud Foundry and Kubernetes systems and workloads."

Discussion and feedback welcome. This is off the top of my head.

**Comment by richard-cox** [comment]
There's a bit of a consistency issue. It looks like this will change the implied product name from `suse stratos cf console` to `suse cap console`, which contradicts a few places where we call the app `suse stratos` or just `stratos`.

Before
![image](https://user-images.githubusercontent.com/18697775/51036794-21f57680-15a6-11e9-8de7-b17643fcca94.png)
After
![image](https://user-images.githubusercontent.com/18697775/51036857-5406d880-15a6-11e9-9177-7e192103c2f1.png)

About Page
![image](https://user-images.githubusercontent.com/18697775/51039081-80255800-15ac-11e9-962f-b49739dc3722.png)

Was toying with the idea of `suse stratos cap console` but it's a bit of a mouthful

![image](https://user-images.githubusercontent.com/18697775/51039392-1d808c00-15ad-11e9-8db0-0ceaac03580f.png)

Another move could be replacing all (visual) references to `Stratos` with `CAP Console`?

![image](https://user-images.githubusercontent.com/18697775/51039617-7fd98c80-15ad-11e9-9bed-7bf9717a97cc.png)

.. and similar changes elsewhere (upgrade page, stratos config and about pages)

@nwmac @troytop Any thoughts?

**Comment by nwmac** [comment]
@troytop I guess the question I have is are we still calling this thing Stratos when its in its SUSE distribution?

We use Stratos quite a bit as shown in the screenshots above - e.g. on the about page - should we be renaming these?

On the login screen, as Richard shows, we show "SUSE Stratos" in the top-left - on small screens, this is all that is shown in the way of title - so this is kind of the short app title - what do you want this to be going forward?

**Comment by troytop** [comment]
Product Marketing has asked that we change to "SUSE Cloud Application Platform" wherever we can. I think we can even drop "Console" from the login page. 

For the other instances of Stratos in the UI, let's discuss them case by case.
