### ISSUE TITLE
K8S View does not render correctly

### ISSUE THREAD

**Issue by nwmac** [SUSE/stratos#79]
Only when build with aot and a prod build.

Side nav gets hidden.
Top navigation header has incorrect vertical spacing - table renders underneath tabs

**Comment by nwmac** [comment]
![screenshot 2018-11-07 at 09 29 57](https://user-images.githubusercontent.com/1955897/48122560-c3431200-e26f-11e8-8dc3-3f4ce24d26e5.png)

**Comment by richard-cox** [comment]
Fixed by #81
